# Generated by Django 5.0.1 on 2024-01-16 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='brand_logo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='LogoOfCompanies'),
            preserve_default=False,
        ),
    ]
