# Generated by Django 5.0.1 on 2024-01-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_companyprofile_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='favicon_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
