# Generated by Django 5.0.1 on 2024-01-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employeeprofile_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='createjobpost',
            name='full_time',
            field=models.BooleanField(default=True),
        ),
    ]
