# Generated by Django 5.0.1 on 2024-01-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_createjobpost_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(default='aA', max_length=150),
            preserve_default=False,
        ),
    ]
