# Generated by Django 5.0.1 on 2024-01-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_companyprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='is_set',
            field=models.BooleanField(default=False),
        ),
    ]
