# Generated by Django 5.0.1 on 2024-01-19 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employeeprofile_is_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('trade_licence', models.SlugField()),
                ('company_size', models.CharField(choices=[('0-10', '0-10'), ('10-50', '10-50'), ('50-100', '50-100'), ('100-500', '100-500'), ('500-1000', '500-1000'), ('1000+', '1000+')], max_length=100)),
                ('brand_logo', models.FileField(upload_to='LogoOfCompanies')),
                ('about', models.TextField(blank=True, null=True)),
                ('stablished_at', models.DateField()),
                ('document', models.FileField(blank=True, null=True, upload_to='ValidCompany/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='brand_logo',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.company'),
        ),
    ]
