# Generated by Django 5.0.1 on 2024-01-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_company_first_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
    ]
