# Generated by Django 5.0.1 on 2024-01-20 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_rename_name_company_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='secret_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
